- name: Freshdesk Playbook - Delete User
  hosts: localhost
  gather_facts: no
  tasks:
    - name: delete_user_from_freshdesk
      uri:
        url: xxx   
        method: DELETE
        user: xxx
        password: X
        force_basic_auth: yes
      register: response
    - name: check_response_status code
      fail:
        msg: "Failed to delete user from Freshdesk. Status code: {{ response.status}}"
      when: response.status !=204

